# $NetBSD$

DISTNAME=	supercat-0.5.5
CATEGORIES=	sysutils
MASTER_SITES=	http://supercat.nosredna.net/

MAINTAINER=	youri.mout@gmail.com	
HOMEPAGE=	http://supercat.nosredna.net/
COMMENT=	supercat is a text colorizer
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes
CONFIGURE_ARGS+= --with-system-directory=${PREFIX}/etc/supercat

.include "../../mk/bsd.pkg.mk"
