# $NetBSD$

DISTNAME=	cwm-xenocara-0.1
CATEGORIES=	wm
MASTER_SITES=	http://saveosx.org/packages/Darwin/2013Q2/x86_64/distfiles/

MAINTAINER=	youri.mout@gmail.com
HOMEPAGE=	http://saveosx.org/packages/Darwin/2013Q2/x86_64/distfiles/
COMMENT=	cwm is a stacking window manager for X
LICENSE=	isc

.include "../../x11/libX11/buildlink3.mk"
.include "../../x11/libXft/buildlink3.mk"
.include "../../x11/libXinerama/buildlink3.mk"
.include "../../x11/libXrandr/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
