# $NetBSD$

DISTNAME=	htop-osx
PKGNAME=	htop-git
CATEGORIES=	sysutils
MASTER_SITES=	http://saveosx.org/packages/Darwin/2013Q2/x86_64/distfiles/

MAINTAINER=	youri.mout@gmail.com
HOMEPAGE=	https://github.com/max-horvath/htop-osx/archive/
COMMENT=	Interactive process viewer
#LICENSE=	# TODO: (see mk/license.mk)

USE_TOOLS+=	gmake 
GNU_CONFIGURE=	yes

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
